# Site settings
title: Thomas ASNAR
email: thomas.asnar@gmail.com
description: "Blog-notes VTOM, SAN, Unix, Sauvegarde. Thomas ASNAR, analyste d'exploitation. Administrateur VTOM, expert sauvegardes, stockage et ordonnancement."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thomas-asnar.github.io" # the base hostname & protocol for your site
github_username:  thomas-asnar
github_url: "https://github.com/thomas-asnar/thomas-asnar.github.io"
permalink: /:title/

timezone: FR
locale: fr_FR

# Build settings
markdown: kramdown

include: [".htaccess"]
exclude: ["bower_components","bower.json", "package.json", "node_modules", "Gemfile", "Gemfile.lock","_build"]


sass:
    style: :compressed

highlighter: pygments