# Site settings
title: Thomas ASNAR | Blog-notes VTOM et informatique
email: thomas.asnar@gmail.com
description: "Blog-notes VTOM, SAN, Unix, Sauvegarde. Thomas ASNAR, analyste d'exploitation. Administrateur VTOM, expert sauvegardes, stockage et ordonnancement."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thomas-asnar.github.io" # the base hostname & protocol for your site
github_username:  thomas-asnar
github_url: "https://github.com/thomas-asnar/thomas-asnar.github.io"
permalink: /:title/

timezone: FR
locale: fr_FR

# Build settings
markdown_ext: "markdown,mkdown,mkdn,mkd,md"# Filtering Content
markdown: kramdown

kramdown:
  input: GFM
  
highlighter: rouge
  
include: [".htaccess"]
exclude: ["bower.json", "package.json", "node_modules", "Gemfile", "Gemfile.lock","_build"]

excerpt_separator: '<!--more-->'

sass:
    style: :compressed

paginate: 30

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jemoji
  - jekyll-seo-tag
